"""Add photo_filename to Student model

Revision ID: 703940af5a9f
Revises: 950dcc80933a
Create Date: 2025-10-30 09:29:47.465212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '703940af5a9f'
down_revision = '950dcc80933a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_filename', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('photo_filename')

    # ### end Alembic commands ###
